# Generated by Django 6.0.3 on 2026-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_aichat_aichatmessage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aichat',
            name='unique_aichat_main_user_solo',
        ),
        migrations.AddConstraint(
            model_name='aichat',
            constraint=models.UniqueConstraint(condition=models.Q(('context_community__isnull', True), ('context_user__isnull', True)), fields=('main_user',), name='unique_aichat_main_user_solo'),
        ),
    ]
